plugins { id 'com.android.library' }
android {
    namespace 'com.limelight'
    compileSdk 36
    defaultConfig {
        minSdk 24
        buildConfigField 'boolean', 'ROOT_BUILD', 'false'
        buildConfigField 'String', 'APPLICATION_ID', '"cn.wangchuan.link.test"'
    }
    buildFeatures { buildConfig true; resValues true }
    buildTypes {
        debug { resValue 'string', 'app_label', '望川高帧率'; resValue 'string', 'app_label_root', '望川高帧率' }
        release { resValue 'string', 'app_label', '望川高帧率'; resValue 'string', 'app_label_root', '望川高帧率' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }
}
dependencies {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.85.2'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.85'
    implementation 'org.jcodec:jcodec:0.2.5'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.jmdns:jmdns:3.6.3'
    implementation 'com.github.cgutman:ShieldControllerExtensions:1.0.1'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}
