param([ValidateSet('Check','Install','Pair')][string]$Mode='Check')

$ErrorActionPreference='Stop'

[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)

. (Join-Path $PSScriptRoot 'usb-preflight.ps1')

$usbAdbPath=Join-Path $PSScriptRoot 'runtime\adb\adb.exe'
if (-not(Test-Path -LiteralPath ([string]$usbAdbPath))) { $usbAdbPath=if($env:ANDROID_HOME){Join-Path $env:ANDROID_HOME 'platform-tools\adb.exe'}else{(Get-Command adb.exe -ErrorAction SilentlyContinue).Source} }
if (-not $usbAdbPath -or -not(Test-Path -LiteralPath ([string]$usbAdbPath))) { throw '缺少 ADB，请完整解压电脑端或设置 ANDROID_HOME。' }
$invokeAdb = {

    param([string[]]$Arguments)

    # Only fixed, non-secret arguments generated by the preflight are accepted.

    foreach($argument in $Arguments) { if($argument -match '["\r\n]'){throw 'Invalid ADB argument.'} }

    $process=[Diagnostics.Process]::new()

    try {

        # PowerShell is case-insensitive and dynamically scoped: the preflight's
        # $Adb callback parameter must never shadow this executable path.
        $process.StartInfo=[Diagnostics.ProcessStartInfo]::new($usbAdbPath, (($Arguments|ForEach-Object {'"'+$_+'"'}) -join ' '))
        $process.StartInfo.UseShellExecute=$false

        $process.StartInfo.CreateNoWindow=$true

        $process.StartInfo.RedirectStandardOutput=$true

        $process.StartInfo.RedirectStandardError=$true

        [void]$process.Start()

        $output=$process.StandardOutput.ReadToEndAsync();$errorOutput=$process.StandardError.ReadToEndAsync()

        if(-not $process.WaitForExit(12000)){try{$process.Kill()}catch{};throw 'USB 检查超时，请重新连接手机后重试。'}

        if($process.ExitCode -ne 0){return 'error: unavailable'}

        return $output.Result

    } finally { $process.Dispose() }

}

$report=Get-SuiLianUsbReport -Adb $invokeAdb
if($Mode -eq 'Pair' -and $report.ready){
    . (Join-Path $PSScriptRoot 'usb-pair-debug.ps1')
    $paired=Connect-SuiLianWirelessDebug -Serial $report.serial -AdbPath $usbAdbPath -Usb $invokeAdb
    $report.items=@($paired)+@($report.items)
}
if($Mode -eq 'Install' -and $report.ready){

    $installed=& (Join-Path $PSScriptRoot 'install-test.ps1') -Serial $report.serial

    $report=Get-SuiLianUsbReport -Adb $invokeAdb

    $report.items=@($installed)+@($report.items)

}

$report.items -join "`r`n`r`n"
